### ISSUE TITLE
RoutingError on sort images

### ISSUE THREAD

**Issue by cdwilhelm** [mkhairi/jquery-datatables#2]
Great gem, thanks for putting this together.
```
Started GET "/images/sort_asc.png" for 127.0.0.1 at 2017-02-17 06:11:54 -0700

ActionController::RoutingError (No route matches [GET] "/images/sort_asc.png"):
```
The images should be included in the pipeline and the css can use image-url to use the asset path.
for example
```css
table.dataTable thead .sorting {
  background-image: image-url("sort_both.png");
}
```
